---

name: 'PR dependency management'
description: 'Manage dependency between PR using the Depends-On keyword.'
author: 'Frederic Lepied'
branding:
  icon: eye
  color: blue
inputs:
  token:
    description: 'Github token'
    mandatory: true
  check-unmerged-pr:
    description: 'Set to true to stop if there are unmerged PR'
    default: false
    type: boolean
  extra-dirs:
    description: 'Other git directories to process (space separated)'
    type: string
runs:
  using: 'node20'
  main: 'dist/index.js'

...
