[project]
name = "depends-on-action"
version = "0.15.0"
description = "GitHub action to use dependent Pull Requests"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["pyyaml>=6.0.2"]

[dependency-groups]
dev = ["pre-commit>=3.0.1", "pytest>=8.3.4"]
