---

name: Get Pull Request Dependencies

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-inject-dependencies:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject dependent PR
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          verbose: true

...
