---

name: Get Pull Request Dependencies

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-inject-dependencies:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, ubuntu-latest]
    steps:

      - name: Python3 version
        run: python3 --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject dependent Pull Requests
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

...
