---

name: Test pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-inject-dependencies:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, macos-latest]
    steps:
      - name: Python3 version
        run: python3 --version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout code (2nd)
        uses: actions/checkout@v4
        with:
          repository: depends-on/depends-on-action
          path: second

      - name: Checkout code (3rd)
        uses: actions/checkout@v4
        with:
          repository: depends-on/depends-on-action
          path: third

      - name: Inject dependent Pull Requests
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          extra-dirs: depends-on-action/second depends-on-action/third

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Build python package
        run: |
          uv sync
          uv venv
          source .venv/bin/activate
          uv pip install setuptools wheel pytest
          uv run python3 setup.py sdist bdist_wheel
          uv pip install dist/*.whl

      - name: Run unit tests
        run: |
          uv run pytest -vv tests/

...
